---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    package: 
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
      update_cache: yes
    when: ansible_distribution == "Kali"