---

- hosts: all
  become: true
  pre_tasks:
  tasks:
  - name: install updates (Kali)
    apt:
      update_cache: yes
    when: ansible_distribution == "Kali"
- hosts: web_servers
  become: true
  tasks:
    
  - name: install apache and php  
    apt:
      name:   
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Kali"

- hosts: [db_server]
  become: true
  tasks:
  - name: install mariadb package (Kali)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Kali"
    